name: Run test containers

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install task manager
        run: sudo apt-get -y install make

      - name: Run docker tests
        run: make container-test
